### ISSUE TITLE
Organizations Contact List

### ISSUE THREAD

**Issue by jonr4u** [CIB-Mango-Tree/CIB-Mango-Tree-Website#4]
List of orgs we can reach out to for publicizing

**Comment by kullman-civictech** [comment]
https://docs.google.com/spreadsheets/d/1Vff-VnnKxfhuFJqdnqu1r_weOxqDVCP30X5Rx9-Pb8Q/edit?usp=drive_link

Spreadsheet with orgs/journalists/individual researchers
